USE [master]
GO
/****** Object:  Database [PharmaAppDB]    Script Date: 3/10/2025 12:19:28 PM ******/
CREATE DATABASE [PharmaAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PharmaAppDB', FILENAME = N'D:\SQL SERVER\MSSQL15.MSSQLSERVER\MSSQL\DATA\PharmaAppDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PharmaAppDB_log', FILENAME = N'D:\SQL SERVER\MSSQL15.MSSQLSERVER\MSSQL\DATA\PharmaAppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PharmaAppDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PharmaAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PharmaAppDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PharmaAppDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PharmaAppDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PharmaAppDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PharmaAppDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [PharmaAppDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PharmaAppDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PharmaAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PharmaAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PharmaAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PharmaAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PharmaAppDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PharmaAppDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PharmaAppDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PharmaAppDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PharmaAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PharmaAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PharmaAppDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PharmaAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PharmaAppDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PharmaAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PharmaAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PharmaAppDB] SET RECOVERY FULL 
GO
ALTER DATABASE [PharmaAppDB] SET  MULTI_USER 
GO
ALTER DATABASE [PharmaAppDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PharmaAppDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PharmaAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PharmaAppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PharmaAppDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PharmaAppDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PharmaAppDB', N'ON'
GO
ALTER DATABASE [PharmaAppDB] SET QUERY_STORE = OFF
GO
USE [PharmaAppDB]
GO

ALTER DATABASE [PharmaAppDB] SET  READ_WRITE 
GO
